name: Safe Main Branch

on:
  pull_request_target:
    branches: main
    types: 
      - opened

jobs:
  run:
    if: ${{ !startsWith(github.head_ref, 'hotfix') || !startsWith(github.head_ref, 'release')}}
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: "Accept hotfix and release branch pull request to main branch"